//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        internal static string AddFriend {
            get {
                return ResourceManager.GetString("AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreshFace.
        /// </summary>
        internal static string FreshFace {
            get {
                return ResourceManager.GetString("FreshFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreshFace Home.
        /// </summary>
        internal static string FreshFaceHome {
            get {
                return ResourceManager.GetString("FreshFaceHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Facebook.
        /// </summary>
        internal static string LoginWithFacebook {
            get {
                return ResourceManager.GetString("LoginWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        internal static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Actions.
        /// </summary>
        internal static string MyActions {
            get {
                return ResourceManager.GetString("MyActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Calendar.
        /// </summary>
        internal static string MyCalendar {
            get {
                return ResourceManager.GetString("MyCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Events.
        /// </summary>
        internal static string MyEvents {
            get {
                return ResourceManager.GetString("MyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Feed.
        /// </summary>
        internal static string MyFeed {
            get {
                return ResourceManager.GetString("MyFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My News.
        /// </summary>
        internal static string MyNews {
            get {
                return ResourceManager.GetString("MyNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My status:.
        /// </summary>
        internal static string MyStatus {
            get {
                return ResourceManager.GetString("MyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stocks.
        /// </summary>
        internal static string MyStocks {
            get {
                return ResourceManager.GetString("MyStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Article - by .
        /// </summary>
        internal static string NewsBy {
            get {
                return ResourceManager.GetString("NewsBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo.
        /// </summary>
        internal static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login using Facebook.  Thanks for trying FreshFace!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
