//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        internal static string AddFriend {
            get {
                return ResourceManager.GetString("AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/ID.
        /// </summary>
        internal static string AddFriendPlaceHolder {
            get {
                return ResourceManager.GetString("AddFriendPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Stock.
        /// </summary>
        internal static string AddStock {
            get {
                return ResourceManager.GetString("AddStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock name.
        /// </summary>
        internal static string AddStockPlaceholder {
            get {
                return ResourceManager.GetString("AddStockPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Price.
        /// </summary>
        internal static string BoughtPrice {
            get {
                return ResourceManager.GetString("BoughtPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change:.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Percent:.
        /// </summary>
        internal static string ChangePercent {
            get {
                return ResourceManager.GetString("ChangePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeYTD:.
        /// </summary>
        internal static string ChangeYTD {
            get {
                return ResourceManager.GetString("ChangeYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Price.
        /// </summary>
        internal static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Stock.
        /// </summary>
        internal static string EditStock {
            get {
                return ResourceManager.GetString("EditStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter friend&apos;s username or id below:.
        /// </summary>
        internal static string EnterFriend {
            get {
                return ResourceManager.GetString("EnterFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter picture URL below:.
        /// </summary>
        internal static string EnterPhoto {
            get {
                return ResourceManager.GetString("EnterPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the stock information below:.
        /// </summary>
        internal static string EnterStock {
            get {
                return ResourceManager.GetString("EnterStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreshFace.
        /// </summary>
        internal static string FreshFace {
            get {
                return ResourceManager.GetString("FreshFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreshFace Home.
        /// </summary>
        internal static string FreshFaceHome {
            get {
                return ResourceManager.GetString("FreshFaceHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High:.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Price:.
        /// </summary>
        internal static string LastPrice {
            get {
                return ResourceManager.GetString("LastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Facebook.
        /// </summary>
        internal static string LoginWithFacebook {
            get {
                return ResourceManager.GetString("LoginWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        internal static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low:.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Cap:.
        /// </summary>
        internal static string MarketCap {
            get {
                return ResourceManager.GetString("MarketCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        internal static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Actions.
        /// </summary>
        internal static string MyActions {
            get {
                return ResourceManager.GetString("MyActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Calendar.
        /// </summary>
        internal static string MyCalendar {
            get {
                return ResourceManager.GetString("MyCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Events.
        /// </summary>
        internal static string MyEvents {
            get {
                return ResourceManager.GetString("MyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Feed.
        /// </summary>
        internal static string MyFeed {
            get {
                return ResourceManager.GetString("MyFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My News.
        /// </summary>
        internal static string MyNews {
            get {
                return ResourceManager.GetString("MyNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stocks.
        /// </summary>
        internal static string MyStocks {
            get {
                return ResourceManager.GetString("MyStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Net Value.
        /// </summary>
        internal static string NetValue {
            get {
                return ResourceManager.GetString("NetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Feed - .
        /// </summary>
        internal static string NewsBy {
            get {
                return ResourceManager.GetString("NewsBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Shares.
        /// </summary>
        internal static string NumShares {
            get {
                return ResourceManager.GetString("NumShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open:.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid Per Share.
        /// </summary>
        internal static string PaidShare {
            get {
                return ResourceManager.GetString("PaidShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share what&apos;s new....
        /// </summary>
        internal static string PostPlaceholder {
            get {
                return ResourceManager.GetString("PostPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shout Out.
        /// </summary>
        internal static string ShoutOut {
            get {
                return ResourceManager.GetString("ShoutOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string StockChange {
            get {
                return ResourceManager.GetString("StockChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StockName {
            get {
                return ResourceManager.GetString("StockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string StockPrice {
            get {
                return ResourceManager.GetString("StockPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Symbol.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Change.
        /// </summary>
        internal static string TodayChange {
            get {
                return ResourceManager.GetString("TodayChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type and press enter to chat.
        /// </summary>
        internal static string TypeForChat {
            get {
                return ResourceManager.GetString("TypeForChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo.
        /// </summary>
        internal static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture URL.
        /// </summary>
        internal static string UploadPhotoPlaceholder {
            get {
                return ResourceManager.GetString("UploadPhotoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login using Facebook.  Thanks for trying FreshFace!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
